
name: Test Internal Action
on: [pull_request]
jobs:
  Test-Internal-Action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./actions/test-action.yml
        with:
          tolog: "My first log"
